#include "flow-sensitive-points-to/flow-sensitive-points-to.dl"
#include "test/core/core.dl"
#include "test/flow-sensitive-points-to/global-access.dl"

nameNode("ra", "ReadVariableNode", "global-property-read.js", 1, 1).
nameNode("rb", "ReadPropertyNode", "global-property-read.js", 1, 1).
expectGlobalAccess($StackNode($Variable($DefaultGlobalScope(), "a")), $Read(), nil, [$HeapNode($ReadAllocation(ra))]) :-
  nodeByName(ra, "ra").
expectGlobalAccess($HeapNode($ReadAllocation(ra)), $Read(), [$PropertyName($StringConstant("b"))], [$HeapNode($ReadAllocation(rb))]) :-
  nodeByName(ra, "ra"),
  nodeByName(rb, "rb").

.output error
.output coreError
.output globalAccessError
