#include "flow-sensitive-points-to/flow-sensitive-points-to.dl"
#include "test/core/core.dl"
#include "test/flow-sensitive-points-to/global-access.dl"

nameNode("ra", "ReadVariableNode", "global-invoke-read.js", 1, 1).
nameNode("ca", "CallNode", "global-invoke-read.js", 1, 1).
nameNode("rb", "ReadPropertyNode", "global-invoke-read.js", 1, 1).

expectGlobalAccess(
  $StackNode($Variable($DefaultGlobalScope(), "a")),
  $Read(),
  nil,
  [$HeapNode($ReadAllocation(ra))]
) :- nodeByName(ra, "ra").

expectGlobalAccess(
  $HeapNode($ReadAllocation(ra)),
  $InvokeFunction(),
  nil,
  [$ReturnValueNode(ca)]
) :- nodeByName(ra, "ra"), nodeByName(ca, "ca").

expectGlobalAccess(
  $ReturnValueNode(ca),
  $Read(),
  [$PropertyName($StringConstant("b"))],
  [$HeapNode($ReadAllocation(rb))]
) :- nodeByName(ca, "ca"), nodeByName(rb, "rb").

.output error
.output coreError
.output globalAccessError
