#include "flow-sensitive-points-to/flow-sensitive-points-to.dl"
#include "test/core/core.dl"
#include "test/flow-sensitive-points-to/global-access.dl"

nameNode("r", "ReadVariableNode", "global-read.js", 1, 9).
expectGlobalAccess($StackNode($Variable($DefaultGlobalScope(), "a")), $Read(), nil, [$HeapNode($ReadAllocation(r))]) :-
  nodeByName(r, "r").

.output error
.output coreError
.output globalAccessError
