#include "flow-sensitive-points-to/flow-sensitive-points-to.dl"
#include "test/core/core.dl"
#include "test/flow-sensitive-points-to/parameter-access.dl"

nameFunction("f", "linked-list.js", 1, 2).
nameNode("rdata", "ReadPropertyNode", "linked-list.js", 4, 9).
nameNode("rnext", "ReadPropertyNode", "linked-list.js", 5, 9).
// First loop iteration: Access `l.data` and `l.next`.
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "l")), $Read(), [$PropertyName($StringConstant("data"))], [$HeapNode($ReadAllocation(rdata))]) :-
  functionByName(f, "f"),
  nodeByName(rdata, "rdata").
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "l")), $Read(), [$PropertyName($StringConstant("next"))], [$HeapNode($ReadAllocation(rnext))]) :-
  functionByName(f, "f"),
  nodeByName(rnext, "rnext").
// Subsequent loop iterations: Access `<result-of-l.next>.data`, `<result-of-l.next>.next`.
expectParameterAccess(f, $HeapNode($ReadAllocation(rnext)), $Read(), [$PropertyName($StringConstant("data"))], [$HeapNode($ReadAllocation(rdata))]) :-
  functionByName(f, "f"),
  nodeByName(rnext, "rnext"),
  nodeByName(rdata, "rdata").
expectParameterAccess(f, $HeapNode($ReadAllocation(rnext)), $Read(), [$PropertyName($StringConstant("next"))], [$HeapNode($ReadAllocation(rnext))]) :-
  functionByName(f, "f"),
  nodeByName(rnext, "rnext").

.output error
.output coreError
.output parameterAccessError
