#include "flow-sensitive-points-to/flow-sensitive-points-to.dl"
#include "test/core/core.dl"
#include "test/flow-sensitive-points-to/parameter-access.dl"

nameFunction("f", "method-invoke.js", 1, 2).
expectParameterAccess(f,  $HeapNode($ParameterAllocation(f, "a")), $Read(), [$PropertyName($StringConstant("x"))], na) :-
  functionByName(f, "f"),
  parameterAccess(f,  $HeapNode($ParameterAllocation(f, "a")), $Read(), [$PropertyName($StringConstant("x"))], na).
expectParameterAccess(f,  $HeapNode($ParameterAllocation(f, "a")), $InvokeMethod(), [$PropertyName($StringConstant("x"))], na) :-
  functionByName(f, "f"),
  parameterAccess(f,  $HeapNode($ParameterAllocation(f, "a")), $InvokeMethod(), [$PropertyName($StringConstant("x"))], na).

.output coreError
.output parameterAccessError
