#include "flow-sensitive-points-to/flow-sensitive-points-to.dl"
#include "test/core/core.dl"
#include "test/flow-sensitive-points-to/parameter-access.dl"

nameFunction("f", "simple-escape.js", 2, 2).
nameNode("ra", "ReadPropertyNode", "simple-escape.js", 5, 1).
nameNode("rc", "ReadPropertyNode", "simple-escape.js", 7, 1).
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "a")), $Read(), [$PropertyName($StringConstant("a"))], [$HeapNode($ReadAllocation(ra))]) :-
  functionByName(f, "f"),
  nodeByName(ra, "ra").
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "a")), $Write(), [$PropertyName($StringConstant("b"))], nil) :-
  functionByName(f, "f").
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "a")), $Read(), [$PropertyName($StringConstant("c"))], [$HeapNode($ReadAllocation(rc))]) :-
  functionByName(f, "f"),
  nodeByName(rc, "rc").
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "a")), $InvokeMethod(), [$PropertyName($StringConstant("c"))], nil) :-
  functionByName(f, "f").
expectParameterAccess(f, $HeapNode($ParameterAllocation(f, "a")), $InvokeFunction(), nil, nil) :-
  functionByName(f, "f").

.output error
.output coreError
.output parameterAccessError
